# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-27 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='a_uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
